- README.md
Keeping docs consistent with the back end repo!
> Added overview from back end repo to keep it consistent

- package-lock.json
- package.json
[Ticket](https://trello.com/c/bVFm7kCR/158-voma-fe-add-styled-components)
> add styled component package

- package-lock.json
- package.json
[ticket](https://trello.com/c/oxdNokvs/151-voma-fe-add-routing-library)
Add react-router-dom package
> Add routing library

- src/lib/CSSReset.js
[Ticket](https://trello.com/c/b9e8VhFQ/162-voma-fe-add-fonts)
> import font and set as default

- src/components/App.js
- src/lib/GlobalStyles.js
- src/pages/NoOnboarding.jsx
[Ticket](https://trello.com/c/K0zpjwWg/170-voma-create-no-onboarding-page)
Page is at `/no-onboarding`
> No onboarding page

- src/components/PrivacyPolicy.jsx
- src/components/StyledFieldset.jsx
- src/lib/GlobalStyles.js
- src/pages/Register.jsx
[ticket](https://trello.com/c/uNsALh7k/164-voma-create-privacy-policy-agreement-page)
Created the Privacy Policy component, copied most of the content from the Code of Conduct component. Added additional styling for the submit button.
> Create Privacy Policy page

- README.md
- client/src/components/App.js
- db/index.js
Add new installation steps to the README
> Update README with new installation steps

- .gitignore
- README.md
- db/sync.js
- docker-compose/docker-compose.yml
- package.json
- server.js
Finish the updated setup instructions by adding steps to create and connect to a local postgres database.
> Add setup instructions to create local database

- db/controllers/volunteers.js
- db/index.js
- server.js
Create CRUD methods and routes for the volunteer model, and clean up the server file a little bit.
> Volunteer crud

- db/controllers/projects.js
- db/controllers/volunteers.js
Update Volunteer and Project controllers for consistency and more robust error handling.
> Controller update

- client/.eslintrc
- client/src/components/App.js
- client/src/pages/Home.jsx
- db/controllers/projects.js
- db/controllers/users.controller.js
- db/controllers/volunteers.js
- package-lock.json
- package.json
- server.js
Update volunteer controller to be more readable
Update controllers
Add findUser controller method and route
Implement sign in flow
> Implement login flow

- client/package-lock.json
- client/package.json
- client/src/pages/Home.jsx
Install Material UI library; add simple MUI button to homepage.
> Install material UI packages and add simple MUI button to home page

- client/src/components/Header.jsx
- client/src/index.js
- client/src/pages/Home.jsx
https://trello.com/c/ZYw9jRAS/302-voma-add-header-to-all-pages-in-voma
- Added a header using the Material AppBar and Toolbar and included it on all pages in the layout file.
- Fixed spacing inconsistency in home page file.
> Added Header component and included it on each page.

- client/src/components/Footer.jsx
- client/src/index.js
Stubbed out the footer component and added it to the general layout file.
> Stubbed out footer component.

- client/package-lock.json
- client/package.json
- client/src/components/App.js
- client/src/components/Header.jsx
- client/src/components/LoginForm.jsx
- client/src/index.js
- client/src/pages/Login.jsx
- Added login page and login form, styled.
- Added global theme settings to default to Material Deep Purple A700.
- Added Mui style library so we can add Material style overrides to components and pages via the mui recommended methods.
> Adding login page and styling top nav.

- client/src/components/VolunteerBox.jsx
- client/src/lib/Requests.js
- client/src/pages/AssignmentBoard.jsx
Pull the volunteers from the db to show on the assignment board page. The design of this page will change, so I left a lot of the values hard coded for now.
> Display all volunteers from the db on the assignment board

- .lando.database.sh
- client/package-lock.json
- client/package.json
- client/src/components/LoginForm.jsx
- client/src/components/RegisterVolunteer/SkillsForm.jsx
- client/src/lib/AuthProvider.js
- client/src/lib/VolunteerProvider.js
- client/src/setupProxy.js
- db/controllers/admins.controller.js
- db/controllers/volunteers.controller.js
- db/models/admin.model.js
- db/models/project.model.js
- db/models/skill.model.js
- db/models/volunteer.model.js
- db/models/volunteerSkills.model.js
- package-lock.json
- package.json
- server.js
Added user authentication and hooked up the login form.
Push requires a resync of your database table structure and `npm install` on both server and client.
- Changed models to use 'underscores' for created_at and updated_at. Need these like this for the lando sync script.
- (Lando Config) Modified the database bash script to seed test data for Projects, Skills, Volunteers, Volunteer Skills. Added associations. Left a few volunteers without an associated project. 
- Pluralized "skill" on FE and BE hook.
- Modified the Lando sync script to push a user into the admin table. Credentials are voma.code.for.chicago@gmail.com with the password "password".
- Added express-session plugin and configured it for development.
- Refactored the login function in the admins controller to work with the …
> Added user authentication.

- client/src/components/App.js
- client/src/lib/AuthProvider.js
- client/src/pages/Logout.jsx
- db/controllers/admins.controller.js
- server.js
- Added 'logout' hook to Express server.
- Redirecting user to login page on logout.
> Added 'logout' hook.

- client/src/lib/VolunteerProvider.js
- db/controllers/volunteers.controller.js
- db/lib/slack.js
- server.js
I was going to make slack 'routes' but aside from the route verifying a volunteer's Slack is registered these functions are probably not going to be stand alone routes but actions within a route. For example, a volunteer is added to a project and there may be a welcome message or something posted in Slack, so I abstracted the main slack functions out into their own file to be included into a route controller as needed.
- Created /db/lib/slack.js to store the Slack bot functions.
- Added slackMessageChannel - takes a channel name with no hash (slackGetChannelId), queries the channel ID and posts a message.
- Added slackMessageUser - messages a user by their Slack ID.
- Moved slackLookupByEmail function into slack.js. 
- Renamed the volunteer slack checking route /api/volunteer/slack, it's …
> Slack Functionality

- .lando.database.sh
- client/.eslintrc
- client/src/components/AssignmentBoard/ProjectBox.jsx
- client/src/components/AssignmentBoard/VolunteerBox.jsx
- client/src/lib/Requests.js
- client/src/pages/AssignmentBoard.jsx
Updates to the Assignment board page.
- Updated fetchVolunteers logic, add fetchProjects function in Requests file.
- Moved styles for the volunteer name box into its component since it is called from multiple parent components.
- Abstracted out the project box into its own component.
- Moved the assignment board componentry into its own folder in `/src/components`.
- Sidebar now displays only unassigned volunteers.
Testing requires a valid user to login to /board and project/volunteer data. I recommend adding volunteers assigned and unassigned to projects.
> Assignment board updates.

- db/index.js
- db/migrations/20220429155442-add-fields-to-project.js
Add migration to update project table. Also add back in `rejectUnauthorized` flag, as I needed it to run the hosted database.
> Create migration to add columns to project table

- client/src/components/App.js
- client/src/components/AssignmentBoard/BoardContainer.jsx
- client/src/components/AssignmentBoard/ProjectInfo.jsx
- client/src/components/AssignmentBoard/VolunteerBox.jsx
- client/src/components/Header.jsx
- client/src/lib/AuthProvider.js
- client/src/pages/AssignmentBoard.jsx
- client/src/pages/Projects.jsx
- db/models/project.model.js
This PR contains the following changes: 
- Update `Project` model in backend (previous PR updated the database schema but neglected to carry the change over to the ORM)
- Turn Assignment board page into reusable component
- Create Project page (read-only)
- Add links to header
> Project page

- db/migrations/20220512145505-add-tasks-to-volunteers.js
- db/models/volunteer.model.js
- server.js
Add migration to add `completedTasks` to Volunteer and update model.
> Add completedTasks to volunteer table

- client/src/components/AssignmentBoard/BoardContainer.jsx
- client/src/components/Header.jsx
- client/src/pages/AssignmentBoard.jsx
- client/src/pages/Projects.jsx
- db/models/volunteer.model.js
Update volunteer page to separate onboarding and ready to assign volunteers in the sidebar.
> Update Volunteer page

- client/src/components/AssignmentBoard/VolunteerModal/VolunteerModal.jsx
- client/src/components/ProjectPage/ProjectInfo.jsx
- db/controllers/volunteers.controller.js
Noticed a couple of bugs as I was working on a different story, so created a PR to fix them.
> Project page bugs

- client/src/components/AssignmentBoard/VolunteerModal/VolunteerModal.jsx
- client/src/components/AssignmentBoard/VolunteerModal/content/ProjectAssignment.jsx
- client/src/components/ProjectPage/ProjectInfo.jsx
- client/src/lib/Requests.js
- db/controllers/projects.controller.js
- db/controllers/slack.controller.js
- db/controllers/testSlack.controller.js
- db/lib/slack/blocks.js
- db/lib/slack/slack.js
- db/migrations/20220730180611-update-project-table.js
- db/models/project.model.js
- server.js
- Create migration to update project table
- Update slack blocks with new project info
- Create functionality to message volunteer with project info
- Create functionality to allow user to confirm yes or no and follow-up action
- Trigger slack messages from the front end
> Project slack message

- client/src/styles/components/Boxes.js
Update volunteer card styles on volunteer page to match current wireframe.
> Update volunteer card styles to match wireframe.

- db/controllers/volunteers.controller.js
Fix bugs related to editVolunteer method.
> Bug fixes for editVolunteer

- db/controllers/event.controller.js
- db/controllers/projects.controller.js
- db/controllers/timeslots.controller.js
- db/controllers/volunteers.controller.js
- db/index.js
- db/migrations/20221120190432-create-event.js
- db/migrations/20221120192127-create-timeslot.js
- db/models/addAssociations.js
- db/models/event.model.js
- db/models/timeslot.model.js
- server.js
Chunky PR, contains the following changes: 
- Create new migrations to add events and timeslots to DB
- Create new models
- Create controller methods and associated routes
- Update existing routes with new associations and functionality
> Events and Timeslots

- client/src/components/ProjectPage/ProjectInfo.jsx
- client/src/pages/Projects.jsx
- Add functionality to pre-select project on project page
- Fix add / edit project bug
> Create link to preselect project on project page

- client/src/components/AssignmentBoard/ProjectContainer.jsx
- client/src/components/AssignmentBoard/VolunteerModal/content/ProjectBox.jsx
- client/src/components/Header.jsx
PR for ticket [Turn project name on project modal into link](https://trello.com/c/ORIF8mW3/85-allow-projects-to-be-linked-to-on-the-project-page)
> Link project name to page

- client/src/components/AssignmentBoard/ProjectContainer.jsx
- client/src/components/AssignmentBoard/VolunteerModal/content/ProjectAssignment.jsx
PR for ticket: [Preselect matching project on the project assignment tab](https://trello.com/c/j9tIG3yA)
> Preselect matching project

- client/src/components/App.js
- client/src/components/Header.jsx
- client/src/components/ProjectPage/ProjectInfo.jsx
- client/src/pages/Home.jsx
- server.js
- Remove locked route from project page
- Turn project page into read-only when user is not authenticated
- Add nav links to volunteer view
- Add a little top-margin on the registration main page
> Allow read-only project page to be accessed by volunteers

- client/src/components/AdminPage/AddAdminModal.jsx
- client/src/components/AdminPage/AdminDetails.jsx
- client/src/components/AdminPage/ChangeAdminPasswordModal.jsx
- client/src/components/App.js
- client/src/lib/AuthProvider.js
- client/src/lib/Requests.js
- client/src/pages/Admin.jsx
- client/src/pages/AdminViewEdit.jsx
- client/src/styles/components/AdminModal.style.js
- db/controllers/admins.controller.js
- server.js
- Create edit admin backend route / controller method
- Create change password route / controller method
- Create frontend page for add, edit, and change password
> Add admin add and edit functionality

- client/package-lock.json
- client/package.json
- client/src/components/AssignmentBoard/BoardContainer.jsx
- client/src/components/AssignmentBoard/VolunteerBox.jsx
- client/src/lib/Requests.js
- client/src/pages/AssignmentBoard.jsx
- client/src/styles/components/VolunteerModal.style.js
Volunteers who have finished onboarding now display an alert icon in their Volunteer Box. Once a user has viewed that card, the icon will go away.
> Volunteer onboarding indicator

- client/public/index.html
- client/src/components/AssignmentBoard/VolunteerBox.jsx
- client/src/components/AssignmentBoard/VolunteerModal/Label.jsx
- client/src/components/Header.jsx
- client/src/lib/Skills.js
- client/src/styles/components/Boxes.js
Volunteer cards should now display the selected skill or no label if no skill is selected. Each skill has its own color/background color, which I took from our Figma designs.
> Volunteer Card Skill Label

- client/public/index.html
- client/src/components/App.js
- client/src/components/StyleTest.jsx
- client/src/lib/GlobalStyles.js
- client/src/styles/components/Typography.js
- Add global styles for headers and body text
- Add color variables to global styles
- Create styled components for labels and other body text
> Add global styles for typography and colors and a few styled components

- client/package-lock.json
- client/package.json
- client/src/components/Modal.jsx
- client/src/components/ProjectPage/ProjectInfo.jsx
- client/src/components/StyleTest.jsx
- client/src/lib/GlobalStyles.js
- client/src/styles/components/Card.style.js
- client/src/styles/components/Modal.style.js
- Create card component styles
- Create modal component styles
- Create simple modal component with basic functionality
> Card and modal

- client/src/components/Button.jsx
- client/src/components/StyleTest.jsx
- client/src/lib/GlobalStyles.js
- client/src/styles/components/Button.style.js
Button component created with the following props: variant, icon, iconSize, and onClick
Button variants include: 
- solid blue
- solid white
- solid red
- outline blue
- fw outline blue
- fw outline white
- text-only red
> Design system button

- client/src/components/PasswordField.jsx
- client/src/components/StyleTest.jsx
- client/src/styles/components/Input.style.js
- Create input field styles
- Create password component 
- Add show / hide password functionality
> Add input field styles and password component

- client/src/components/Accordion.jsx
- client/src/components/StyleTest.jsx
- client/src/styles/components/Accordion.style.js
Please let me know if you'd like me to make any updates to the accordion component I've created. Thanks!
> Create accordion functional component

- client/src/components/ContentBox.jsx
- client/src/components/StyleTest.jsx
- client/src/styles/components/ContentBox.style.js
- client/src/styles/components/HeaderLink.style.js
Create content box and Header Link components.
> Content box

- db/migrations/20230720022108-update-volunteer.js
- db/models/volunteer.model.js
- Add `projectAssignmentAccepted` and `active` fields
- Remove `onboardingAttendedAt` and `oneOnOneAttendedAt` fields
> Update volunteer table

- client/src/components/AssignmentBoard/BoardContainer.jsx
- client/src/components/AssignmentBoard/ProjectCard.jsx
- client/src/components/Header.jsx
- client/src/components/ProjectPage/ProjectSidebar.jsx
- client/src/components/StyleTest.jsx
- client/src/lib/GlobalStyles.js
- client/src/pages/AssignmentBoard.jsx
- client/src/pages/Projects.jsx
- client/src/styles/components/BoardContainer.style.js
- client/src/styles/components/BoardSidebar.style.js
- client/src/styles/components/Card.style.js
- client/src/styles/pages/ProjectPage.style.js
Update styles of project sidebar.
> Restyle project board sidebar

- client/src/components/App.js
- client/src/components/ArchivePage/ArchiveAccordion.jsx
- client/src/components/ArchivePage/ArchiveContainer.jsx
- client/src/components/ArchivePage/DeleteProjectModal.jsx
- client/src/components/ArchivePage/ReactivateProjectModal.jsx
- client/src/components/AssignmentBoard/BoardContainer.jsx
- client/src/components/ProjectPage/ArchiveProjectModal.jsx
- client/src/components/ProjectPage/ProjectContainer.jsx
- client/src/components/ProjectPage/ProjectSettings.jsx
- client/src/components/ProjectPage/ProjectSidebar.jsx
- client/src/lib/GlobalStyles.js
- client/src/lib/Requests.js
- client/src/pages/ArchivedProjects.jsx
- client/src/styles/components/BoardContainer.style.js
- client/src/styles/components/Card.style.js
- client/src/styles/pages/ArchivePage.style.js
- client/src/styles/pages/ProjectPage.style.js
- db/controllers/projects.controller.js
- db/migrations/20240328011231-add-active-to-project.js
- db/models/project.model.js
- server.js
- Update project table to include `isActive` field
- Add `isActive` to project model
- Create archive and reactivate controller methods and routes
- Create archive page
- Add archive / reactivate / delete / fetch archived methods to FE request lib
- Finish project settings tab to include archive button
> Archive project
